### ISSUE TITLE
ImportError:

### ISSUE THREAD

**Issue by loophe** [daodao2007/e001#1]
运行的时候报错了：
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from web3 import Web3, HTTPProvider
  File "/usr/local/lib/python3.8/dist-packages/web3/__init__.py", line 9, in <module>
    from web3.main import (
  File "/usr/local/lib/python3.8/dist-packages/web3/main.py", line 55, in <module>
    from web3.eth import (
  File "/usr/local/lib/python3.8/dist-packages/web3/eth.py", line 69, in <module>
    from web3.contract import (
  File "/usr/local/lib/python3.8/dist-packages/web3/contract.py", line 135, in <module>
    from web3.types import (  # noqa: F401
**ImportError: cannot import name 'CallOverrideParams' from 'web3.types' (/usr/local/lib/python3.8/dist-packages/web3/types.py)**
少了types.py的修改内容

**Comment by daog1** [comment]
我刚fork了web.py，我直接改在那个里面吧，这样大家方便一些。

**Comment by daog1** [comment]
https://github.com/daodao2007/web3.py,你试试这个。

**Comment by loophe** [comment]
可以，与预期结果一致
